# Ensure that no class is orphaned (excluding top level 'disease driver' class)

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?class
WHERE {
  ?class a owl:Class .
  FILTER NOT EXISTS { ?class rdfs:subClassOf ?parent }
  FILTER NOT EXISTS { ?class owl:deprecated true }
  FILTER (?class != <http://purl.obolibrary.org/obo/TRANS_0000000>)
}